### PR TITLE
#change gtaa query inlcude hidden labels

### PR DESCRIPTION
**Pull request by wmelder**
as was signaled "zelensky" didn't produce results, while "zelenski" does.
Both should produce results, because "zelensky" is definitely in one of the hiddenLabels.
As it turns out, the default full text index doesn't include the hiddenlabels, therefor we changed the text query a bit..

### CODE REVIEW

**Comment by ddeboer** [comment]
Thanks!

**Comment by ddeboer** [comment]
@wmelder However, this seems to cause [timeouts for GTAA persoonsnamen](https://termennetwerk.netwerkdigitaalerfgoed.nl/?q=zelenski&datasets=https://data.beeldengeluid.nl/id/datadownload/0026).

**Comment by wmelder** [comment]
@ddeboer The timeouts should be fixed because of the text query. But indeed, the termennetwerk demonstrator does seem to give a terminology source unavailable. Will look into it.

**Comment by wmelder** [comment]
@ddeboer please confirm that the gtaa-persoonsnamen.rq query is not used anymore. It should be replaced with the gtaa.rq, which uses textQuery and is fast enough in itself to search even large conceptschemes like Persoonsnamen.

**Comment by ddeboer** [comment]
> @ddeboer please confirm that the gtaa-persoonsnamen.rq query is not used anymore. It should be replaced with the gtaa.rq, which uses textQuery and is fast enough in itself to search even large conceptschemes like Persoonsnamen.

It is still used: 

https://github.com/netwerk-digitaal-erfgoed/network-of-terms/blob/e32df4b8b3d1228222da01bc416ed24084ea0a9c/packages/network-of-terms-catalog/catalog/datasets/gtaa-persoonsnamen.jsonld#L34

Shouldn’t it be?

**Comment by wmelder** [comment]
no, that is still the old query that doesn't use the fulltext functionality. 
All GTAA conceptSchemes can now use the same search query

**Comment by ddeboer** [comment]
Ah, you mentioned so in #767 but didn’t actually commit the required changes. I can do so now.

**Pull request merged**
