### PR TITLE
feat: Sort GeoNames by relevance score

### PR DESCRIPTION
**Pull request by ddeboer**
Ref #1064
Replace #1065

### CODE REVIEW

**Comment by wmelder** [comment]
Question: you're using `vrank:simpleRank` on an instance of a `skos:Concept`. The formal definition of the property describes it should be an `owl:Thing` as the domain:
```turtle
vrank:simpleRank a rdf:Property, owl:DatatypeProperty, owl:FunctionalProperty;
    owl:propertyChainAxiom (vrank:hasRank vrank:rankValue) ;
    rdfs:label "rank";
    rdfs:comment "Directly connects owl:Thing with ranking values.";
    rdfs:domain owl:Thing;
    rdfs:range xsd:float .
```
How are we allowed to still use it?

**Comment by ddeboer** [comment]
Good question. As far as I can see, `owl:Thing` represents the set of all individuals, making all user-defined `owl:Class`es, including `skos:Concept` subclasses of `owl:Thing`. The domain `owl:Thing` then includes `skos:Concept`.

**Pull request merged**
