### PR TITLE
feat!: Add link to dataset page

### PR DESCRIPTION
**Pull request by ddeboer**
BREAKING CHANGE: for custom catalogs, add a `schema:mainEntityOfPage`
property to each dataset.

### CODE REVIEW

**Comment by ddeboer** [comment]
@rschalkrce I used [the property `schema:mainEntityOfPage`](https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/#dataset-overview). Please check all my suggestions in the catalog, paying particular attention to the `https://???` values that I could not find any good webpage for.

**Review by rschalkrce — CHANGES_REQUESTED** [review]
@ddeboer ,

I've added a URL to `mainEntityOfPage` where I could find one. Some are still open. For these I would suggest to continue to use the `url` value for now (I have not done that yet).

**Pull request merged**
